name: Build iOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Shared Kotlin
        run: ./gradlew :composeApp:assembleDebug # Збирає спільну логіку
      - name: Build iOS App
        run: |
          cd iosApp
          pod install # Це обов'язково для iOS
          xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -configuration Release CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
