name: Build iOS

on: [push]

jobs:
  build:
    name: Build iOS Project
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Shared Kotlin
        run: ./gradlew :composeApp:assembleDebug

      - name: Prepare iOS Dependencies
        run: |
          # Спробуємо зібрати проєкт через Gradle, щоб він згенерував необхідні файли для iOS
          ./gradlew :iosApp:podInstall || echo "No podInstall task found, skipping..."
        
      - name: Build iOS App
        run: |
          cd iosApp
          # Перевіримо, чи є Podfile після виконання Gradle
          if [ -f "Podfile" ]; then
            pod install
            xcodebuild clean build \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
          else
            echo "Podfile still not found! Checking directory contents:"
            ls -R
            exit 1
          fi
